version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
    - app
    ports:
    - 80:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - "MYSQL_ROOT_PASSWORD=secret"
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USERNAME=homestead"
    ports:
    - "33061:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
    - 8080:80

volumes:
  dbdata:
